{
    "version": "3",
    "services": {
        "apache": {
            "build": {
                "context": "./",
                "dockerfile": "Dockerfile"
            },
            "volumes": [
                "./:/var/www/html/"
            ],
            "ports": [
                "80:80"
            ],
            "depends_on": [
            ]
        }
    }
}